# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
          checkLatest: true
        displayName: 'Install Node.js'
      - script: |
          npm install yarn
          yarn install
          yarn run build
        displayName: 'install yarn, app install and build'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: 
      vmImage: $(vmImageName)
    steps:
      - script: |
          firebase deploy
        displayName: 'firebase deploy'